---
exclude: \.idea|test/remote-cases/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: requirements-txt-fixer
      - id: mixed-line-ending
      - id: check-toml
      - id: detect-private-key
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9
    hooks:
      - id: ruff
        args: [ --fix, --preview ]
      - id: ruff-format
        args: [ --preview ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        additional_dependencies:
            - types-PyYAML==6.0.11
            - types-attrs==19.1.0
            - types-paramiko==2.11.6
            - types-pkg_resources==0.1.3
            - types-python-dateutil==2.8.19
            - types-requests==2.28.9
            - types-toml==0.10.8
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.100.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
  - repo: local
    hooks:
      - id: test
        name: Run tests
        entry: make test
        language: system
        types_or: [python, shell]
        pass_filenames: false
        require_serial: true
      - id: lint-compilation-lambda
        name: Lint compilation-lambda
        entry: bash -c 'cd compilation-lambda && npm install && npm run lint'
        language: system
        files: ^compilation-lambda/.*\.(js|json|yml)$
        pass_filenames: false
      - id: lint-events-lambda
        name: Lint events-lambda
        entry: bash -c 'cd events-lambda && npm install && npm run lint'
        language: system
        files: ^events-lambda/.*\.(js|json|yml)$
        pass_filenames: false
