name: Compiler discovery

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: choice
        default: staging
        required: true
        options:
        - staging
        - beta
        - prod
      branch:
        description: 'Branch'
        default: 'main'
        required: true
      buildnumber:
        description: 'Build number'
        default: ''
        required: true
      skip_msvc_check:
        description: 'Skip MSVC check'
        default: no
        type: choice
        options:
        - no
        - yes
        required: true

jobs:
  compilerdiscovery:
    runs-on: ['admin']

    steps:
    - name: Update infra
      run: cd /home/ubuntu/infra && git pull
    - name: Set build number ${{ github.event.inputs.buildnumber }}
      run: ce --env runner builds set_current ${{ github.event.inputs.buildnumber }} --branch ${{ github.event.inputs.branch }} --confirm
    - name: Start runner
      run: ce runner start
    - name: Update infra on runner
      run: ce runner pull
    - name: Do Compiler discovery
      run: ce runner discovery
    - name: Upload discovered compilers
      if: ${{ github.event.inputs.skip_msvc_check }}
      run: ce runner uploaddiscovery ${{ !github.event.inputs.environment }} --skip-msvc-check False ${{ github.event.inputs.buildnumber }}
    - name: Upload discovered compilers without checking MSVC
      if: ${{ github.event.inputs.skip_msvc_check }}
      run: ce runner uploaddiscovery ${{ github.event.inputs.environment }} --skip-msvc-check True ${{ github.event.inputs.buildnumber }}
    - name: Shut down runner
      run: ce runner stop
