name: CEFS consolidation

on:
  # TODO: enable
  # schedule:
  #   - cron: '15 6 * * *'
  workflow_dispatch:
    inputs:
      filter:
        description: Things to consolidate (empty means all)
        default: ''
        required: false
      max-size:
        description: Maximum size of things to consolidate
        default: 20G
        required: false
jobs:
  consolidate:
    if: github.repository == 'compiler-explorer/infra'
    runs-on: [ 'self-hosted', 'ce', 'linux', 'x64' ]
    steps:
      - name: Start from a clean directory
        uses: AutoModality/action-clean@v1.1.0
      - uses: actions/checkout@v4
      - name: Set up environment
        run: make ce
      - name: Consolidate ${{ github.event.inputs.filter }} into ${{ github.event.inputs.max-size }} chunks
        # TODO: finally sort out permissions for this. I hate sudo
        # TODO: remote `--debug` once we're happy
        run: sudo bin/ce_install --debug cefs consolidate --reconsolidate --max-size ${{ github.event.inputs.max-size }} ${{ github.event.inputs.filter }}
