name: Build cross compiler

on:
  workflow_dispatch:
    inputs:
      compilertype:
        description: 'Compilertype'
        default: 'gcc'
        required: true
      architecture:
        description: 'Architecture'
        default: 'arm64'
        required: true
      version:
        description: 'Compiler version'
        default: '7.5.0'
        required: true
      configversion:
        description: 'Config version'
        default: '7.5.0'
        required: true

jobs:
  buildcross:
    runs-on: ['admin']

    steps:
    - name: Update infra
      run: cd /home/ubuntu/infra && git pull
    - name: Build compiler
      run: /home/ubuntu/infra/one-off-cross.sh ${{ github.event.inputs.compilertype }} build.sh ${{ github.event.inputs.architecture }} ${{ github.event.inputs.version }} ${{ github.event.inputs.configversion }}
