name: Squashfs-ify the compilers

on:
  schedule:
    - cron: '15 6 * * *'
  workflow_dispatch:
    inputs:
      squash:
        description: Things to squash (empty means all)
        default: ''
        required: false
jobs:
  squash:
    runs-on: [ 'self-hosted', 'ce', 'ubuntu' ]
    steps:
      - name: Start from a clean directory
        uses: AutoModality/action-clean@v1.1.0
      - uses: actions/checkout@v3
      - name: Set up environment
        run: make ce
        # relies on this being empty on cron
      - name: Squash ${{ github.event.inputs.squash }}
        run: bin/ce_install squash ${{ github.event.inputs.squash }}
