name: status

on:
  push:

jobs:
  status:
    name: Testy mctest
    runs-on: ubuntu-latest

    steps:
      - name: printy
        run: echo "My run id is '${GITHUB_RUN_ID}'"
      - name: Fetch check run ids
        id: fetch
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{repo}/actions/runs/{run_id}/jobs
          repo: ${{ github.repository }}
          run_id: ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Echo check run ids
        run: echo "job ids - ${{ toJSON(fromJSON(steps.fetch.outputs.data).jobs.*.id) }}
